jobs:
    main:
        requires: [~pr, ~commit]
        image: node:8
        steps:
            - echo: echo hi
            - teardown-meta: |
                meta set meta.status.coverage '{"status":"SUCCESS","message":"Coverage is above 80%."}'
                meta set meta.status.pendingTest '{"status":"PENDING","message":"Still working on it."}'
